import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/layout/header'
import Footer from './ui/layout/footer'
import { ThemesProviders, AOSProviders, ReduxProviders } from './providers'
import { fetchImagesCompany } from './lib/data'
import { CompanyModel } from './lib/definitions'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Ecommerse  - SysSoft Integra',
//   description: 'Generated by SysSoft Integra',
//   icons: 'public/favicon.ico',
// }

// Función para obtener los datos del backend
async function getMetadataFromBackend() {
      const company = await fetchImagesCompany() as CompanyModel;
    return {
      title: company.nombreEmpresa || 'Ecommerse',
      description: company.acercaNosotros || 'Descripción del negocio',
      favicon: company.rutaIcon || 'favicon.svg'
      // favicon: 'https://docs.nestjs.com/assets/logo-small-gradient.svg'
    };
  
}

// Generador dinámico de metadata
export async function generateMetadata(): Promise<Metadata> {
  const metadata = await getMetadataFromBackend();
  
  return {
    title: metadata.title,
    description: metadata.description,
    icons: {
      icon: metadata.favicon,
      apple: metadata.favicon,
      // icon: 'https://docs.nestjs.com/assets/logo-small-gradient.svg',
      // apple: 'https://docs.nestjs.com/assets/logo-small-gradient.svg',
    },
  }
}

export const viewport: Viewport = {
  initialScale: 1.0,
  width: 'device-width',
  userScalable: false,
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="es" suppressHydrationWarning>
        <body className={`${inter.className} bg-[#f8f8f8] dark:bg-[#1a1a1a] `}>
        <ReduxProviders>
          <ThemesProviders>
            <AOSProviders>
              <div id='root'>
                <Header />
                <main>
                  {children}
                </main>
                <Footer />
              </div>
            </AOSProviders>
          </ThemesProviders>
        </ReduxProviders>
      </body>
    </html>
  )
}
