import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/main/header'
import Footer from './ui/main/footer'
import { ThemesProviders, AOSProviders, ReduxProviders } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-[#f8f8f8] dark:bg-[#1a1a1a] `}>
        <ReduxProviders>
          <ThemesProviders>
            <AOSProviders>
              <div id='root'>
                <Header />
                <main>
                  {children}
                </main>
                <Footer />
              </div>
            </AOSProviders>
          </ThemesProviders>
        </ReduxProviders>
      </body>
    </html>
  )
}
