import type { Metadata, Viewport } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { importClientComponents } from '@/app/lib/utils/importClientComponents'
import { ThemesProviders, AOSProviders, ReduxProviders } from './providers'
import { fetchCompanyInfo, fetchCompanyWhatsapp, fetchListBranchs} from './lib/data'
import { BranchModel, CompanyModel } from './lib/definitions'
import Whatsapp from './ui/component/import-muneli/whatsapp'

const inter = Open_Sans({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Ecommerse  - SysSoft Integra',
//   description: 'Generated by SysSoft Integra',
//   icons: 'public/favicon.ico',
// }

// Función para obtener los datos del backend
async function getMetadataFromBackend() {
  const company = await fetchCompanyInfo() as CompanyModel;
  return {
    title: company.nombreEmpresa || 'Ecommerse',
    description: company.acercaNosotros || 'Descripción del negocio',
    favicon: company.rutaIcon || 'favicon.svg'
    // favicon: 'https://docs.nestjs.com/assets/logo-small-gradient.svg'
  };

}

// Generador dinámico de metadata
export async function generateMetadata(): Promise<Metadata> {
  const metadata = await getMetadataFromBackend();

  return {
    title: metadata.title,
    description: metadata.description,
    icons: {
      icon: metadata.favicon,
      apple: metadata.favicon,
      // icon: 'https://docs.nestjs.com/assets/logo-small-gradient.svg',
      // apple: 'https://docs.nestjs.com/assets/logo-small-gradient.svg',
    },
  }
}

export const viewport: Viewport = {
  initialScale: 1.0,
  width: 'device-width',
  userScalable: false,
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const branchs = await fetchListBranchs() as BranchModel[];
  const company = await fetchCompanyInfo() as CompanyModel;
  const whatsapp = await fetchCompanyWhatsapp() as CompanyModel;

  const { Header, Footer } = await importClientComponents();

  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${inter.className} bg-[#f8f8f8] dark:bg-[#1a1a1a] `}>
        <ReduxProviders>
          <ThemesProviders>
            <AOSProviders>
              <div id='root'>
                <Header company={company} />
                <main>
                  {children}
                </main>
                <Footer company={company} branchs={branchs} />
                <Whatsapp
                  title={whatsapp.tituloWhatsapp}
                  message={whatsapp.mensajeWhatsapp}
                  number={whatsapp.numeroWhatsapp}
                />
              </div>
            </AOSProviders>
          </ThemesProviders>
        </ReduxProviders>
      </body>
    </html>
  )
}
